version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    restart: always

  redis:
    image: redis

  celery:
    build: .
    command: celery -A backend_challenge worker --loglevel=debug
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=backend_challenge.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A backend_challenge beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=debug
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=backend_challenge.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    restart: always

volumes:
  postgres_data:
