# Generated by Django 3.2.20 on 2023-07-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('barcode', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('imported', 'Imported')], max_length=20)),
                ('imported_t', models.DateTimeField()),
                ('url', models.URLField()),
                ('product_name', models.CharField(max_length=550)),
                ('quantity', models.CharField(max_length=550)),
                ('categories', models.CharField(max_length=550)),
                ('packaging', models.CharField(max_length=550)),
                ('brands', models.CharField(max_length=550)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
