# Generated by Django 3.2.20 on 2023-07-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
